In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('sentimentdataset.csv', encoding='latin-1')

In [4]:
df = data.copy()

In [5]:
df.head()

Unnamed: 0.1  Unnamed: 0  \
0             0           0   
1             1           1   
2             2           2   
3             3           3   
4             4           4   

                                                Text    Sentiment  \
0   Enjoying a beautiful day at the park!        ...   Positive     
1   Traffic was terrible this morning.           ...   Negative     
2   Just finished an amazing workout! 💪       ...   Positive     
3   Excited about the upcoming weekend getaway!  ...   Positive     
4   Trying out a new recipe for dinner tonight.  ...   Neutral      

             Timestamp            User     Platform  \
0  2023-01-15 12:30:00   User123          Twitter     
1  2023-01-15 08:45:00   CommuterX        Twitter     
2  2023-01-15 15:45:00   FitnessFan      Instagram    
3  2023-01-15 18:20:00   AdventureX       Facebook    
4  2023-01-15 19:55:00   ChefCook        Instagram    

                                     Hashtags  Retweets  Likes       Country  \
0   #Nature #Park                                  15.0   30.0     USA         
1   #Traffic #Morning                               5.0   10.0     Canada      
2   #Fitness #Workout                              20.0   40.0   USA           
3   #Travel #Adventure                              8.0   15.0     UK          
4   #Cooking #Food                                 12.0   25.0    Australia    

   Year  Month  Day  Hour  
0  2023      1   15    12  
1  2023      1   15     8  
2  2023      1   15    15  
3  2023      1   15    18  
4  2023      1   15    19

In [7]:
df = df[["Text","Sentiment"]]

In [8]:
df.head()

Text    Sentiment
0   Enjoying a beautiful day at the park!        ...   Positive  
1   Traffic was terrible this morning.           ...   Negative  
2   Just finished an amazing workout! 💪       ...   Positive  
3   Excited about the upcoming weekend getaway!  ...   Positive  
4   Trying out a new recipe for dinner tonight.  ...   Neutral

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Text       732 non-null    object
 1   Sentiment  732 non-null    object
dtypes: object(2)
memory usage: 11.6+ KB


In [10]:
import nltk
nltk.download('punkt')
nltk.download("stopwords")

[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


False

In [11]:
from nltk.tokenize import word_tokenize, RegexpTokenizer

In [13]:
word_tokens = [word_tokenize(i) for i in df["Text"]]

In [14]:
word_tokens[:5]

[['Enjoying', 'a', 'beautiful', 'day', 'at', 'the', 'park', '!'],
 ['Traffic', 'was', 'terrible', 'this', 'morning', '.'],
 ['Just', 'finished', 'an', 'amazing', 'workout', '!', 'ð\x9f\x92ª'],
 ['Excited', 'about', 'the', 'upcoming', 'weekend', 'getaway', '!'],
 ['Trying', 'out', 'a', 'new', 'recipe', 'for', 'dinner', 'tonight', '.']]

In [15]:
removal = RegexpTokenizer(r"\w+")

In [17]:
newsentiments = [removal.tokenize(i) for i in df["Text"]]

In [18]:
newsentiments[:5]

[['Enjoying', 'a', 'beautiful', 'day', 'at', 'the', 'park'],
 ['Traffic', 'was', 'terrible', 'this', 'morning'],
 ['Just', 'finished', 'an', 'amazing', 'workout', 'ð', 'ª'],
 ['Excited', 'about', 'the', 'upcoming', 'weekend', 'getaway'],
 ['Trying', 'out', 'a', 'new', 'recipe', 'for', 'dinner', 'tonight']]

In [19]:
newString = [" ".join(i) for i in newsentiments]

In [20]:
newString[:5]

['Enjoying a beautiful day at the park',
 'Traffic was terrible this morning',
 'Just finished an amazing workout ð ª',
 'Excited about the upcoming weekend getaway',
 'Trying out a new recipe for dinner tonight']

In [21]:
from nltk.corpus import stopwords

In [22]:
stopWords = set(stopwords.words("english"))

In [23]:
newStrTokens = [word_tokenize(i) for i in newString]

In [24]:
newStrTokens[:5]

[['Enjoying', 'a', 'beautiful', 'day', 'at', 'the', 'park'],
 ['Traffic', 'was', 'terrible', 'this', 'morning'],
 ['Just', 'finished', 'an', 'amazing', 'workout', 'ð', 'ª'],
 ['Excited', 'about', 'the', 'upcoming', 'weekend', 'getaway'],
 ['Trying', 'out', 'a', 'new', 'recipe', 'for', 'dinner', 'tonight']]

In [25]:
updatedStrings = [[word for word in i if not word in stopWords] for i in newStrTokens]

In [26]:
updatedStrings[:5]

[['Enjoying', 'beautiful', 'day', 'park'],
 ['Traffic', 'terrible', 'morning'],
 ['Just', 'finished', 'amazing', 'workout', 'ð', 'ª'],
 ['Excited', 'upcoming', 'weekend', 'getaway'],
 ['Trying', 'new', 'recipe', 'dinner', 'tonight']]

In [27]:
dummy = [" ".join(i) for i in updatedStrings]

In [28]:
dummy[:5]

['Enjoying beautiful day park',
 'Traffic terrible morning',
 'Just finished amazing workout ð ª',
 'Excited upcoming weekend getaway',
 'Trying new recipe dinner tonight']

In [29]:
df["Text"] = dummy

C:\Users\sahil\AppData\Local\Temp\ipykernel_17448\2158252250.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Text"] = dummy


In [30]:
df.head()

Text    Sentiment
0        Enjoying beautiful day park   Positive  
1           Traffic terrible morning   Negative  
2  Just finished amazing workout ð ª   Positive  
3   Excited upcoming weekend getaway   Positive  
4   Trying new recipe dinner tonight   Neutral

In [31]:
df["Sentiment"].value_counts()

 Positive           44
 Joy                42
 Excitement         32
 Neutral            14
 Contentment        14
                    ..
 Adrenaline          1
 Harmony             1
 ArtisticBurst       1
 Radiance            1
 Elegance            1
Name: Sentiment, Length: 279, dtype: int64

In [32]:
df.shape

(732, 2)

In [34]:
sentimentList = df["Sentiment"].value_counts().head().index.tolist

In [64]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
import warnings
warnings.filterwarnings("ignore")

In [65]:
tk = Tokenizer()

In [66]:
tk.fit_on_texts(df["Text"])

In [67]:
tokens = tk.texts_to_sequences(df["Text"])

In [68]:
tokens[:5]

[[162, 307, 6, 428],
 [1074, 1075, 308],
 [309, 643, 1076, 223, 84, 429],
 [644, 72, 85, 645],
 [127, 1, 310, 430, 431]]

In [69]:
vocab_size = len(tk.word_index)+1

In [70]:
vocab_size

2471

In [71]:
seq = tk.texts_to_matrix(df["Text"])

In [72]:
seq[:5]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [73]:
max_length = max([len(i) for i in seq])

In [74]:
max_length

2471

In [75]:
pad_seq = pad_sequences(seq, maxlen=max_length, padding="post")

In [76]:
pad_seq[:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [77]:
from sklearn.preprocessing import LabelEncoder

In [78]:
le = LabelEncoder()

In [79]:
lbl = le.fit_transform(df["Sentiment"])

In [80]:
lbl

array([214, 195, 214, 214, 197, 214, 214, 214, 195, 197, 214, 195, 214,
       214, 197, 214, 214, 214, 197, 195, 214, 214, 214, 214, 214, 214,
       214, 214, 214, 214, 214, 214, 214, 214, 214, 214, 214, 214, 214,
       214, 214, 214, 214, 214, 214, 214, 214, 214, 214, 214, 214, 214,
        15, 115, 240,  83, 137, 173, 184,  13, 100,   4,   9,  26,  80,
       257,   0,   6,  16,  31,  38,  52, 111, 176, 218, 248,  15, 115,
       240,  83, 137, 173, 184,  13, 100,   4,   9,  26,  80, 257,   0,
         6,  16,  31,  38,  52, 111, 176, 218, 248,   0, 111,  31,  38,
        51, 110, 176, 218, 247,  89, 109,  57, 245, 132, 151,  95,  47,
       261,  22, 102, 124, 235,  89, 109,  57, 245, 132, 151,  95,  47,
       261,  22, 102, 124, 235,  89,  89, 109,  57, 245, 132, 151,  95,
        46, 261,  22, 102, 125, 234,  89, 109,  57, 245, 132, 151,  95,
        47, 261,  22, 102, 125, 234,  88,  75, 135, 180, 170, 231, 123,
        36,  19, 165, 149, 105, 227,  84,  74, 135, 178, 170, 23

In [81]:
cls = le.classes_.tolist()

In [82]:
cls

[' Acceptance   ',
 ' Acceptance      ',
 ' Accomplishment ',
 ' Admiration ',
 ' Admiration   ',
 ' Admiration    ',
 ' Adoration    ',
 ' Adrenaline     ',
 ' Adventure ',
 ' Affection    ',
 ' Amazement ',
 ' Ambivalence ',
 ' Ambivalence     ',
 ' Amusement    ',
 ' Amusement     ',
 ' Anger        ',
 ' Anticipation ',
 ' Anticipation  ',
 ' Anxiety   ',
 ' Anxiety         ',
 ' Appreciation  ',
 ' Apprehensive ',
 ' Arousal       ',
 ' ArtisticBurst ',
 ' Awe ',
 ' Awe    ',
 ' Awe          ',
 ' Awe           ',
 ' Bad ',
 ' Betrayal ',
 ' Betrayal      ',
 ' Bitter       ',
 ' Bitterness ',
 ' Bittersweet ',
 ' Blessed       ',
 ' Boredom ',
 ' Boredom         ',
 ' Breakthrough ',
 ' Calmness     ',
 ' Calmness      ',
 ' Captivation ',
 ' Celebration ',
 ' Celestial Wonder ',
 ' Challenge ',
 ' Charm ',
 ' Colorful ',
 ' Compassion',
 ' Compassion    ',
 ' Compassionate ',
 ' Confidence    ',
 ' Confident ',
 ' Confusion ',
 ' Confusion    ',
 ' Confusion       ',
 ' Connecti

In [83]:
df.head()

Text    Sentiment
0        Enjoying beautiful day park   Positive  
1           Traffic terrible morning   Negative  
2  Just finished amazing workout ð ª   Positive  
3   Excited upcoming weekend getaway   Positive  
4   Trying new recipe dinner tonight   Neutral

In [84]:
model = Sequential([
    Embedding(vocab_size, 64, input_length=max_length),
    SimpleRNN(64, activation="relu"),
    Dense(64, activation="relu"),
    Dense(10, activation="softmax")
])

In [85]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy",metrics=["accuracy"])

In [86]:
model.fit(pad_seq, lbl, epochs=30, verbose=1)     

Epoch 1/30


InvalidArgumentError: Graph execution error:

Detected at node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\sahil\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>

  File "C:\Users\sahil\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance

  File "C:\Users\sahil\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 711, in start

  File "C:\Users\sahil\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start

  File "C:\Users\sahil\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever

  File "C:\Users\sahil\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once

  File "C:\Users\sahil\anaconda3\Lib\asyncio\events.py", line 80, in _run

  File "C:\Users\sahil\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue

  File "C:\Users\sahil\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one

  File "C:\Users\sahil\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell

  File "C:\Users\sahil\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 729, in execute_request

  File "C:\Users\sahil\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 411, in do_execute

  File "C:\Users\sahil\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 531, in run_cell

  File "C:\Users\sahil\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3006, in run_cell

  File "C:\Users\sahil\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3061, in _run_cell

  File "C:\Users\sahil\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner

  File "C:\Users\sahil\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3266, in run_cell_async

  File "C:\Users\sahil\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3445, in run_ast_nodes

  File "C:\Users\sahil\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code

  File "C:\Users\sahil\AppData\Local\Temp\ipykernel_17448\2183500492.py", line 1, in <module>

  File "C:\Users\sahil\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler

  File "C:\Users\sahil\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1807, in fit

  File "C:\Users\sahil\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1401, in train_function

  File "C:\Users\sahil\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1384, in step_function

  File "C:\Users\sahil\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1373, in run_step

  File "C:\Users\sahil\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1151, in train_step

  File "C:\Users\sahil\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1209, in compute_loss

  File "C:\Users\sahil\anaconda3\Lib\site-packages\keras\src\engine\compile_utils.py", line 277, in __call__

  File "C:\Users\sahil\anaconda3\Lib\site-packages\keras\src\losses.py", line 143, in __call__

  File "C:\Users\sahil\anaconda3\Lib\site-packages\keras\src\losses.py", line 270, in call

  File "C:\Users\sahil\anaconda3\Lib\site-packages\keras\src\losses.py", line 2454, in sparse_categorical_crossentropy

  File "C:\Users\sahil\anaconda3\Lib\site-packages\keras\src\backend.py", line 5775, in sparse_categorical_crossentropy

Received a label value of 267 which is outside the valid range of [0, 10).  Label values: 164 267 110 56 87 139 195 216 191 258 128 179 235 131 178 10 39 58 38 22 221 207 172 217 28 141 64 56 254 214 28 224
	 [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_4947]

In [101]:
new_text = "Trying new recipe dinner tonigh"

In [102]:
new_tk = tk.texts_to_sequences([new_text])

In [103]:
new_tk

[[127, 1, 310, 430]]

In [104]:
new_pad_seq = pad_sequences(new_tk, maxlen=max_length, padding="post")

In [105]:
new_pad_seq

array([[127,   1, 310, ...,   0,   0,   0]])

In [106]:
pred = model.predict(new_pad_seq)

1/1 [==============================] - 0s 79ms/step


In [107]:
pred

array([[0.10264783, 0.10055485, 0.09996774, 0.0974127 , 0.09898345,
        0.09966146, 0.10043038, 0.10009911, 0.10023338, 0.10000908]],
      dtype=float32)

In [108]:
np.argmax(pred)

0

In [109]:
cls[3]

' Admiration '